markdown: rdiscount
auto: true

exclude: ["README.md", "LICENSE.md", "TODO.md", "build", "test"]

owner-name: Florian Margaine
owner-page: http://www.margaine.com
owner-email: florian@margaine.com

license: Copyright © 2012 Florian Margaine. Tous droits réservés.

