markdown: rdiscount
auto: true

# You can put your configuration options for Jekyll in here.
# Jekyll's default configuration is already pretty good, and github only adds
# pygments and safe as command line options when running Jekyll.
#
# If you test your site locally, and have pygments installed, you should use the
# following command to preview your site:
# $ jekyll --pygments --safe
#
# For more on github pages go to http://pages.github.com/
