markdown: rdiscount
auto: true

exclude: ["README.md", "LICENSE.md", "TODO.md", "build", "test"]

url: http://127.0.0.1:4000

owner-name: your name
owner-page: your homepage
owner-email: your email

license: your license of choice